### ISSUE TITLE
Asterisk is mistaken as comment when in middle of line

### ISSUE THREAD

**Issue by ThatIsAPseudo** [etienne-monier/LedgerTools#1]
Hi there, I found that the syntax highlighting considers `*` in the middle of a line as a comment, whereas it should only do so if it is at the beginning of a line, [as specified in the Ledger documentation](https://www.ledger-cli.org/3.0/doc/ledger3.html#Commenting-on-your-Journal) :

> Comments are generally started using a `;`. However, in order to increase compatibility with other text manipulation programs and methods, four additional comment characters are valid if used **at the beginning of a line**: `#`, `|`, and `*` and `%`.

Indeed, `*` can be used to declare inline operations, such as `(X * Y EUR)`

_Screenshot of the end of the line being highlighted as a comment :_ 

<img width="169" alt="Capture d’écran 2021-02-15 à 18 31 58" src="https://user-images.githubusercontent.com/17936055/107978481-bec04480-6fb4-11eb-9595-3939298bdccf.png">

Could you please fix that ?
Many thanks for your work !

**Comment by etienne-monier** [comment]
Ok, that's fixed.
Yet, there is some remaining issue, it's that the scope of "(26.40 * 0.5 EUR)" will not be good. I've designed the amount to be only numeric (e.g. 26.40) and I did not consider math operations. This will appear the same with the color palette, so that is not so important for me. If any problem, let me know.

Thanks for your nice message :)

**Comment by ThatIsAPseudo** [comment]
Thank you for answering so quickly !

As for my feedback, I have a minor issue that is a popup `No ledger definition filename in settings.` whenever I save a ledger file (the syntax highlighting works though). (_Update: I just set an empty file as `definition filename` for now, but I don't remember it to be an issue with the previous versions of LedgerTools_)

I did some tests however, and found there may be a ambiguity in the Ledger documentation : it is said that `#`, `|`, `*` and `%` can be used at the beginning of a line, but it implies "without the indent".
It means that
```
# This is a valid comment (as expected)
* Same
2011/12/11  Something Sweet
    # This is also a valid comment, even though there is an indent before the '#'
    * This is a valid comment too
    Expenses:Food                  $10.00 ; This is a valid inline comment
    Assets:Credit Union:Checking          # This is NOT a valid comment and will raise an error on parsing
```

Weirdly enough,
```
2011/12/11  Something Sweet
    Expenses:Food                  $10.00
    Assets:Credit Union:Checking
               # This is a valid comment, even though there is a random number of spaces before the '#'
```

The current syntax highlighting does not reflect that, since `#`, `|`, `*` and `%` can only be used at the very beginning of a line, not after space characters.

I personnally only use `;` for commenting so I don't mind, but I just wanted to point it out to you ;)
Once again thanks for your help !
___
I don't know if you'll see this message as the issue is closed, so I'll ping you here juste to be sure @etienne-monier

**Comment by etienne-monier** [comment]
I don't understand. I updated the syntax according to the documentation as you mentioned. Is everything ok now ?

**Comment by ThatIsAPseudo** [comment]
> As for my feedback, I have a minor issue that is a popup No ledger definition filename in settings. whenever I save a ledger file (the syntax highlighting works though). (Update: I just set an empty file as definition filename for now, but I don't remember it to be an issue with the previous versions of LedgerTools)

I thought I found another issue, but nevermind everything's good for that part.

___

> I did some tests however, and found there may be a ambiguity in the Ledger documentation : it is said that `#`, `|`, `*` and `%` can be used at the beginning of a line, but it implies "without the indent".

Je pense que ça sera plus simple si j'explique en français : dans la documentation il est effectivement marqué que les caractères `#`, `|`, `*` et `%` peuvent servir de balise de commentaire s'ils sont positionnés en début de ligne.

Mais j'ai fait des tests, et il se trouve que ces caractères sont considérés par Ledger comme des commentaire s'ils sont indentés, là on LedgerTools ne les considérera comme des commentaires que s'ils sont le tout premier caractère de leur ligne.

Je joins une capture d'écran, toutes les lignes où il est marqué `(SHOULD BE GRAY)` sont des commentaires valides pour Ledger, et devraient donc être colorés en gris par LedgerTools.

![](https://user-images.githubusercontent.com/17936055/109472926-a51a0500-7a6a-11eb-8f94-d4da237f370f.png)

**Il faut comprendre la documentation comme suit : les caractères `#`, `|`, `*` et `%` peuvent servir de balise de commentaire s'ils sont en début de ligne, *éventuellement précédés par des espaces ou des tabulations*.**

J'espère avoir été assez clair, je reste à disposition en cas de question !

**Comment by etienne-monier** [comment]
Ok, alors j'ai mis cela à jour. Ce sera pris en compte lors de la prochaine release.
Merci :)

**Comment by ThatIsAPseudo** [comment]
Merci à vous :)
