### ISSUE TITLE
Open as UTF-8 encoded

### ISSUE THREAD

**Issue by Pinjasaur** [etienne-monier/LedgerTools#3]
Noticing some behavior where the Search Account / Payee chokes on a definition file with non-ASCII characters e.g., emoji or emoticons.

I _think_ the trivial fix is using `open` with `encoding="utf-8"`.

Thanks again for this package!

**Comment by etienne-monier** [comment]
Hi !

Thanks for this post.
Are you using Linux ? If yes, what returns `echo $LANG` in your terminal ?

Using emoji in payee worked for me as my system default encoding *is* UTF-8. If this is not your default, that explains the bug.
 
I'm waiting your command output just to be sure.

**Comment by Pinjasaur** [comment]
> Are you using Linux ? If yes, what returns echo $LANG in your terminal ?

I'm seeing this behavior on macOS, so kinda.

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H114
$ echo $LANG
en_US.UTF-8
```

A minimal definition file example:

```ledger
; 🤑
commodity USD
```

Produces this (copied from the Sublime Text command prompt):

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "/Users/paul/Library/Application Support/Sublime Text 3/Installed Packages/LedgerTools.sublime-package/SearchAccountPayee.py", line 57, in run
  File "/Users/paul/Library/Application Support/Sublime Text 3/Installed Packages/LedgerTools.sublime-package/SearchAccountPayee.py", line 36, in get_info
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 2: ordinal not in range(128)
```

Incidentally I'm not seeing this on Windows. Have not been doing Ledger/Sublime Text work on a straight Linux machine to know if the behavior matches my experience on Mac.

Thanks!

**Comment by etienne-monier** [comment]
Ok, I then modified default encoding to utf8. I'm drawing a new release right now.
Thanks for your help !
